//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.PsoQ
{
    [Serializable]
    public class SpawnRequest : Message
    {
        public const string k_RosMessageName = "pso_q_msgs/Spawn";
        public override string RosMessageName => k_RosMessageName;

        public float x;
        public float y;
        public float z;
        public string name;

        public SpawnRequest()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
            this.name = "";
        }

        public SpawnRequest(float x, float y, float z, string name)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.name = name;
        }

        public static SpawnRequest Deserialize(MessageDeserializer deserializer) => new SpawnRequest(deserializer);

        private SpawnRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "SpawnRequest: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
